# Generated by Django 5.2.7 on 2025-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBOAccessToken',
            fields=[
                ('oid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('oid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('roles', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=list)),
            ],
        ),
    ]
