# Generated by Django 5.1.4 on 2025-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('supplier', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('justification', models.TextField(max_length=1000)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0)),
                ('ship_to', models.TextField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=200)),
                ('phone', models.TextField(blank=True, max_length=12, null=True)),
                ('address1', models.TextField(max_length=100)),
                ('address2', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('zip', models.TextField(max_length=10)),
                ('country', models.TextField(max_length=50)),
            ],
        ),
    ]
