# Generated by Django 5.2.7 on 2025-11-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=dict),
        ),
    ]
