# Generated by Django 5.1.4 on 2025-07-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchaseorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrder',
            new_name='PurchaseOrders',
        ),
    ]
