# Generated by Django 5.2.7 on 2025-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_permissions_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
