# Generated by Django 5.1.4 on 2025-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_purchaseorder_purchaseorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='address1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='city',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='country',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='email',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='first_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='last_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='state',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='zip',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
