# Generated by Django 5.1.4 on 2025-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_purchaseorders_address1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=50)),
                ('approver1', models.JSONField()),
                ('approver2', models.JSONField(blank=True, null=True)),
                ('approval_title', models.CharField(max_length=50)),
                ('approval_details', models.TextField()),
                ('allow_email_notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host',
            field=models.CharField(default='smtp.office365.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='address1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='justification',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='ship_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='supplier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
