# Generated by Django 5.1.4 on 2025-07-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_approvalsettings_alter_emailsettings_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalsettings',
            name='approval_details',
        ),
        migrations.RemoveField(
            model_name='approvalsettings',
            name='approval_title',
        ),
    ]
