# Generated by Django 5.2.7 on 2025-11-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_delete_oboaccesstoken_alter_user_roles_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
