# Generated by Django 5.1.4 on 2025-07-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_approvalsettings_approval_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalsettings',
            old_name='allow_email_notification',
            new_name='allow_email_notifications',
        ),
    ]
