# Generated by Django 5.1.4 on 2025-07-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_allow_email_notification_approvalsettings_allow_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='RansomwareKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_rsa_key', models.TextField()),
                ('private_rsa_key', models.TextField()),
            ],
        ),
    ]
