# Generated by Django 5.2.7 on 2025-11-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
