# Generated by Django 5.2.7 on 2025-10-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ransomwarekeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBOAccessToken',
            fields=[
                ('oid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.TextField()),
                ('expires_in', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RansomwareKeys',
        ),
    ]
