# Generated by Django 5.2.7 on 2025-10-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_oboaccesstoken_delete_ransomwarekeys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oboaccesstoken',
            old_name='expires_in',
            new_name='expires_at',
        ),
    ]
