# Generated by Django 5.2.7 on 2025-11-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='additional_details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
