# Generated by Django 5.2.7 on 2025-11-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_expires_in_oboaccesstoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('requester', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('change_type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('impact', models.IntegerField(default=0)),
                ('risk', models.IntegerField(default=0)),
                ('team', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
