# Generated by Django 5.2.7 on 2025-11-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auditlog_additional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=['User.Read']),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=['User']),
        ),
    ]
