# Generated by Django 5.2.7 on 2025-11-28 17:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_permissions_alter_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='endpoint',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=core.models.default_permissions),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=core.models.default_roles),
        ),
    ]
