# Generated by Django 5.2.7 on 2026-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_endpoint_auditlog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
