# Generated by Django 5.2.7 on 2026-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditlog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='oid',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_details',
            field=models.JSONField(default=dict),
        ),
    ]
