# Generated by Django 5.2.7 on 2026-04-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_auditlog_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(max_length=40),
        ),
    ]
