# Generated by Django 5.2.7 on 2026-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_auditlog_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='remote_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(default='firefox', max_length=255),
        ),
    ]
