# Generated by Django 5.2.7 on 2026-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditlog_remote_ip_auditlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='remote_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
