# Generated by Django 5.2.7 on 2026-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_auditlog_remote_ip_alter_auditlog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='api_key_used',
            field=models.BooleanField(default=False),
        ),
    ]
