# Generated by Django 5.2.7 on 2026-04-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auditlog_api_key_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
