# Generated by Django 5.2.7 on 2026-04-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_auditlog_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
