# Generated by Django 5.2.7 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AppUser',
            new_name='AppUsers',
        ),
        migrations.RenameModel(
            old_name='AuditLog',
            new_name='AuditLogs',
        ),
    ]
