# Generated by Django 5.2.7 on 2026-01-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=50)),
                ('approver1', models.JSONField()),
                ('approver2', models.JSONField(blank=True, null=True)),
                ('allow_email_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('requester', models.EmailField(blank=True, max_length=50, null=True)),
                ('approver', models.EmailField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open'), (3, 'On Hold'), (4, 'Awaiting Approval'), (5, 'In Progress'), (6, 'Testing')], default=1)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0)),
                ('impact', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0)),
                ('risk', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0)),
                ('implementation_date', models.DateTimeField()),
                ('requires_downtime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.office365.com', max_length=50)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_username', models.CharField(max_length=50)),
                ('email_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('supplier', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('justification', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0)),
                ('ship_to', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZohoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='1000.3fdf4848d0a324a00ca98e7759583f0c.bc5484982c4b2a1b568b1b98543679cf')),
                ('expires_at', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
