# Generated by Django 5.2.7 on 2026-01-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
