# Generated by Django 5.2.7 on 2026-04-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_timestamp_changes_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalSettings',
        ),
        migrations.DeleteModel(
            name='PurchaseOrders',
        ),
    ]
