# Generated by Django 5.2.7 on 2026-04-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_approvalsettings_delete_purchaseorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='approver',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='impact',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0),
        ),
        migrations.AlterField(
            model_name='changes',
            name='implementation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0),
        ),
        migrations.AlterField(
            model_name='changes',
            name='requester',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changes',
            name='risk',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0),
        ),
        migrations.AlterField(
            model_name='changes',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Closed'), (1, 'Open'), (3, 'On Hold'), (4, 'Awaiting Approval'), (5, 'In Progress'), (6, 'Testing')], default=1),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_host',
            field=models.CharField(default='smtp.office365.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_port',
            field=models.PositiveSmallIntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zohotoken',
            name='expires_at',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
