# Generated by Django 5.2.7 on 2026-04-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_changes_approver_alter_changes_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.DeleteModel(
            name='ZohoToken',
        ),
    ]
